# Generated by Django 5.0.7 on 2024-07-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, verbose_name='Folio')),
                ('tproducto', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('prodoembarc', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=50)),
                ('nombrechof', models.CharField(max_length=50)),
                ('pesoton', models.FloatField()),
                ('pesolib', models.FloatField()),
                ('horallegada', models.TimeField()),
                ('horaapertura', models.TimeField()),
                ('horacarga', models.TimeField()),
                ('horasalida', models.TimeField()),
                ('tiempoenfila', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'weight',
            },
        ),
    ]
