# Generated by Django 5.0.7 on 2024-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_alter_weight_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='tproducto',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
