# Generated by Django 5.0.7 on 2024-08-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_alter_weight_tproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='nombrechof',
            field=models.CharField(max_length=50, verbose_name='nombrechof'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='prodoembarc',
            field=models.CharField(max_length=50, verbose_name='poe'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='proveedor',
            field=models.CharField(max_length=50, verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='tproducto',
            field=models.CharField(choices=[('cayenne', 'Cayenne'), ('arbol', 'Arbol')], max_length=50, verbose_name='tipoproducto'),
        ),
    ]
