# Generated by Django 5.0.7 on 2024-08-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0004_alter_weight_fecha_alter_weight_nombrechof_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='pesoton',
            new_name='pesokg',
        ),
    ]
