# Generated by Django 5.0.7 on 2024-08-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0006_alter_weight_pesolib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='pesokg',
            new_name='pesoton',
        ),
        migrations.AlterField(
            model_name='weight',
            name='pesolib',
            field=models.FloatField(),
        ),
    ]
