# Generated by Django 5.0.7 on 2024-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0007_rename_pesokg_weight_pesoton_alter_weight_pesolib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='tproducto',
            field=models.CharField(choices=[('cayenne', 'Cayenne'), ('chipotle', 'Chipotle')], max_length=50, verbose_name='tipoproducto'),
        ),
    ]
