# Generated by Django 5.0.7 on 2024-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0008_alter_weight_tproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='pesolib',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
