# Generated by Django 5.0.7 on 2024-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaciado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaciado',
            name='hdecomiezov',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vaciado',
            name='hdefinalizacionv',
            field=models.TimeField(),
        ),
    ]
