# Generated by Django 5.0.7 on 2024-09-05 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weight', '0008_alter_weight_tproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdesal', models.CharField(max_length=30)),
                ('pdehumedad', models.CharField(max_length=30)),
                ('lotsal', models.CharField(max_length=30)),
                ('lotsal2', models.CharField(max_length=30)),
                ('lotsal3', models.CharField(max_length=30)),
                ('kgdesal', models.CharField(max_length=30)),
                ('ltdeagua', models.CharField(max_length=30)),
                ('tanque1', models.CharField(max_length=30)),
                ('tanque2', models.CharField(max_length=30)),
                ('tanque3', models.CharField(max_length=30)),
                ('lttanque1', models.CharField(max_length=30)),
                ('lttanque2', models.CharField(max_length=30)),
                ('lttanque3', models.CharField(max_length=30)),
                ('ltpasta', models.CharField(max_length=30)),
                ('kgpasta', models.CharField(max_length=30)),
                ('kgdesperdiciados', models.CharField(max_length=30)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='weight.weight')),
            ],
        ),
    ]
