# Generated by Django 5.0.7 on 2024-09-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='totalpasta',
            field=models.FloatField(default=0.0),
        ),
    ]
