# Generated by Django 5.0.7 on 2024-09-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_production_totalpasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='pdehumedad',
        ),
        migrations.AlterField(
            model_name='production',
            name='totalpasta',
            field=models.CharField(default=0.0, max_length=30),
        ),
    ]
