# Generated by Django 5.0.7 on 2024-09-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_production_pdehumedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='pdehumedad',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
