# Generated by Django 5.0.7 on 2024-09-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_production_pdehumedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='kgdesal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='kgdesperdiciados',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='production',
            name='kgpasta',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='production',
            name='ltdeagua',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='ltpasta',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='production',
            name='pdehumedad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='production',
            name='pdesal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='totalpasta',
            field=models.FloatField(default=0.0),
        ),
    ]
