# Generated by Django 5.0.7 on 2024-09-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_production_kgdesal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='kgdesal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='kgdesperdiciados',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='kgpasta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='ltdeagua',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='ltpasta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='totalpasta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
