# Generated by Django 5.0.7 on 2024-09-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_production_kgdesal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='totalpasta',
            field=models.FloatField(default=0.0),
        ),
    ]
