# Generated by Django 5.0.7 on 2024-09-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_production_totalpasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='totalpasta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
