# Generated by Django 5.0.7 on 2024-09-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_production_totalpasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='lttanque1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='lttanque2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='lttanque3',
            field=models.FloatField(),
        ),
    ]
