# Generated by Django 5.0.7 on 2024-09-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weight', '0008_alter_weight_tproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('causa', models.CharField(max_length=50)),
                ('tanque', models.CharField(max_length=30)),
                ('tanque2', models.CharField(max_length=30)),
                ('hdecomiezo', models.TimeField()),
                ('hdef', models.TimeField()),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidades', to='weight.weight')),
            ],
        ),
    ]
