# Generated by Django 5.0.7 on 2024-09-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calidad',
            name='ttotal',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
