# Generated by Django 5.0.7 on 2024-08-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weight', '0004_alter_weight_fecha_alter_weight_nombrechof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bol', models.CharField(max_length=50)),
                ('selloasup', models.CharField(max_length=50)),
                ('sellodesc', models.CharField(max_length=50)),
                ('selloasup2', models.CharField(max_length=50)),
                ('sellodesc2', models.CharField(max_length=50)),
                ('sellorep', models.CharField(max_length=50)),
                ('tanque1', models.CharField(max_length=50)),
                ('tanque2', models.CharField(max_length=50)),
                ('horacarga', models.TimeField()),
                ('horafcarga', models.TimeField()),
                ('tiempocarga', models.CharField(max_length=20)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipas', to='weight.weight')),
            ],
            options={
                'db_table': 'pipas',
            },
        ),
    ]
