# Generated by Django 5.0.7 on 2024-08-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipas', '0001_initial'),
        ('weight', '0008_alter_weight_tproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipas',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipa', to='weight.weight'),
        ),
    ]
