# Generated by Django 5.0.7 on 2024-08-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipas', '0003_pipas_bombac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipas',
            name='bombac',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
